# Generated by cucumber-sinatra. (2012-06-13 16:58:22 -0400)

ENV['RACK_ENV'] = 'test'
require 'bundler/setup'
require File.join(File.dirname(__FILE__), '..', '..', 'main.rb')

require 'capybara'
require 'capybara/cucumber'
require 'capybara-webkit'
require 'test/unit/assertions'
require 'database_cleaner'
require 'database_cleaner/cucumber'

DatabaseCleaner.strategy = :truncation

Capybara.app = TwitterClone
Capybara.javascript_driver = :webkit

class TwitterCloneWorld
  include Capybara::DSL
  include Test::Unit::Assertions
end

Before do
  DatabaseCleaner.start
  User.create(handle: "BigAl", following: [])
  User.create(handle: "-__-", following: ["BigAl"])
end

After do
  DatabaseCleaner.clean
end

World do
  TwitterCloneWorld.new
end
