# Generated by cucumber-sinatra. (2012-06-13 16:58:22 -0400)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'main.rb')

require 'capybara'
require 'capybara/cucumber'
require 'test/unit/assertions'
require 'database_cleaner'
require 'database_cleaner/cucumber'

DatabaseCleaner.strategy = :truncation

Capybara.app = TwitterClone

class TwitterCloneWorld
  include Capybara::DSL
  Capybara.javascript_driver = :webkit
  include Test::Unit::Assertions
end

Before do
  DatabaseCleaner.start
  User.create(handle: "BigAl", following: [])
end

After do
  DatabaseCleaner.clean
end

World do
  TwitterCloneWorld.new
end
